config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # get "/cocktails", to: "cocktails#index"
  # get "/cocktails/new", to: "cocktails#new", as: "new_cocktail"
  # post "/cocktails", to: "cocktails#create" 
  # get "/cocktails/:id", to: "cocktails#show", as: "cocktail"
  # get "/cocktails/:cocktail_id/doses/new", to: "doses#new" as: "new_cocktail_dose"
  # post "/cocktails/:cocktail_id/doses/", to: "doses#create" as: "cocktail_doses"
  # delete "/doses/:id", to: "doses#destroy"
  resources :cocktails do
   resources :doses, only:[:new, :create]
   resources :reviews, only:[:new, :create]
  end
  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
 has_many :doses, dependent: :destroy
 has_many :ingredients, through: :doses
 has_many :reviews, dependent: :destroy
 validates :name, presence: true, uniqueness: true
 has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
 has_many :doses, dependent: :destroy
 validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, :rating, presence: true
  validates :cocktail, presence: true
  validates :rating, inclusion: { in: 1..5,
    message: "%{value} is not a valid rating" }
  validates :rating, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

 before_action :set_cocktail, only: [:show, :destroy, :edit, :update] 

 def index
  @cocktails = Cocktail.all
 end

 def show
  @cocktail = Cocktail.find(params[:id])
  @reviews = Review.all
 end

 def new
  @cocktail = Cocktail.new
 end

 def create
  @cocktail = Cocktail.new(cocktail_params)
  if @cocktail.save
   redirect_to cocktail_path(@cocktail)
  else
   render :new
  end
 end

 def edit
 end

 def update
  @cocktail.update(cocktail_params)
  redirect_to cocktail_path(@cocktail)
 end

 def destroy
  @cocktail.destroy
  redirect_to cocktails_path
 end

 private

 def set_cocktail
  @cocktail = Cocktail.find(params[:id])
 end

 def cocktail_params
  params.require(:cocktail).permit(:name, :photo, :description)
 end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

 def new
  @cocktail = Cocktail.find(params[:cocktail_id])
  @dose = Dose.new
 end

 def create
  @dose = Dose.new(dose_params)
  @cocktail = Cocktail.find(params[:cocktail_id])
  @dose.cocktail = @cocktail
  if @dose.save
   redirect_to cocktail_path(@cocktail)
  else
   render :new
  end
 end

 def destroy
  @dose = Dose.find(params[:id])
  @dose.destroy
  redirect_to cocktail_path(@dose.cocktail)
 end

 private

 def dose_params
  params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
 end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

 def new
  @cocktail = Cocktail.find(params[:cocktail_id])
  @review = Review.new
 end

 def create
  @review = Review.new(review_params)
  @cocktail = Cocktail.find(params[:cocktail_id])
  @review.cocktail = @cocktail
  if @review.save
   redirect_to cocktail_path(@cocktail)
  else
   render :new
  end
 end

 private
 def review_params
  params.require(:review).permit(:rating, :content)
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
 def meta_title
   content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
 end

 def meta_description
   content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
 end

 def meta_image
   meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
   # little twist to make it work equally with an asset or a url
   meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
 end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <h1 class='mt-4'>Add/Edit description</h1>
  <%= simple_form_for(@cocktail) do |f|  %>
    <%= f.input :description %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <h1 class='mt-4'>Cocktails</h1>
  <div class="cocktail-index row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="cocktail-card">
          <%= cl_image_tag cocktail.photo.key, class: "card-img-top rounded-lg", height: 300, width: 300, crop: :fill %>
          <div class="card-body">
            <h1><%= link_to cocktail.name, cocktail_path(cocktail)%></h1>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1 class='mt-4'>New cocktail</h1>
  <%= simple_form_for(@cocktail) do |f|  %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Create your cocktail", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1 class='mt-4'><%= @cocktail.name %></h1>
  <div class="cocktail-container">
    <p> <%= cl_image_tag @cocktail.photo.key, width: 400, height: 400, class: "cocktail-show-img" %></p>
    <div class="dose-container">
      <div class="ingredient-container">
        <h2> Ingredients </h2>
        <ul class="list-group">
          <% @cocktail.doses.each do |dose| %>
            <div class="ingredient-content">
              <li> <i class="fas fa-smoking"></i>  <%= dose.description %>
                <%= dose.ingredient.name %>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <span><i class="far fa-trash-alt"></i></span>
                <% end %>
              </li>
            </div>
          <% end %>
        </ul>
        <%= render "/doses/new" %>
        <button type="button" onclick="document.getElementById('dose-form').style.display='block'; this.style.visibility='hidden';", class="btn btn-primary my-2">Add an ingredient</button>
      </div>
      <div class="description-container">
        <h2>Description</h2>
        <div class="description-content">
          <% if @cocktail.description.nil? %>
            <p> <i class="fas fa-smoking"></i> There is no description for this cocktail.</p>
          <% else %>
            <p><i class="fas fa-smoking"></i> <%= @cocktail.description %></p>
          <% end %>
        </div>
        <%= link_to  "Edit Description", edit_cocktail_path(@cocktail), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="reviews-container mb-3">
    <h2>Reviews</h2>
    <ul class="list-group">
      <% if @cocktail.reviews.empty? %>
        <p>There is no review for this cocktail</p>
      <% else %>
        <% @cocktail.reviews.each do |review| %>
          <div class="review-content">
            <li><%= '⭐️' * review.rating %></li>
            <li><i class="fas fa-smoking"></i> <%= review.content %></li>
          </div>
        <% end %>
      </ul>
    <% end %>
    </div>
    <%= render "reviews/new" %>
    <button type="button" onclick="document.getElementById('review-form').style.display='block'; this.style.visibility='hidden';", class="btn btn-primary my-2">Add a review</button>
  </div>
</div>

app/views/doses/_new.html.erb
<div id="dose-form">
  <h2 class='mt-2'>New dose</h2>
  <%= simple_form_for [@cocktail, Dose.new] do |f|  %>
    <%= f.input :description %>
    <%= f.association :ingredient, type: 'select', collection: Ingredient.all %>
    <%= f.submit "Submit your ingredient", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1 class='mt-2'>New dose</h1>
  <%= simple_form_for [@cocktail, @dose] do |f|  %>
    <%= f.input :description %>
    <%= f.association :ingredient, type: 'select', collection: Ingredient.all %>
    <%= f.submit "Submit your ingredient", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="<%= meta_description %>">
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <div style="height: 70px;">
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/reviews/_new.html.erb
<div id="review-form">
  <h2 class='mt-4'>Add a new review</h2>
  <%= simple_form_for [ @cocktail, Review.new ] do |f| %>
    <%= f.input :rating, type: 'select', collection: [1, 2, 3, 4, 5] %>
    <%= f.input :content %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="footer-up">
      <div class="info-footer">
        <i class="fas fa-envelope" id='envelope-footer'></i>
        <a href="Email:Renaud.archerf@gmail.com">Renaud.archerf@gmail.com</a>
      </div>
      <div class="social-footer">
        <a id="git", href="https://github.com/renaudaf", target="_blank"><i class="fab fa-github"></i></a>
        <a id="linkedin", href="https://www.linkedin.com/in/renaud-archer-fortin/", target="_blank"><i class="fab fa-linkedin"></i></a>
      </div>
      <p class="legal-footer">© Copyright 2020 RAF, All Rights Reserved.</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="/cocktails">
    <i class="fas fa-glass-martini-alt"></i>
    Renaud's Casa Di Mama
  </a>
  <a href="/cocktails/new" class='btn btn-sm btn-outline-secondary'>Add A Cocktail</a>
</nav>